// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIYKjoqUp98FA2gFeVZPFA0Op_RG0_9-g',
    appId: '1:394471131335:web:de5b1ecaa0285b628b56e2',
    messagingSenderId: '394471131335',
    projectId: 'insightfolio-3eaf4',
    authDomain: 'insightfolio-3eaf4.firebaseapp.com',
    storageBucket: 'insightfolio-3eaf4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh2_zYxchEeNdul_JfSt4GV-IkcGnxkBo',
    appId: '1:394471131335:android:3e32ca7e121dbc728b56e2',
    messagingSenderId: '394471131335',
    projectId: 'insightfolio-3eaf4',
    storageBucket: 'insightfolio-3eaf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBKkBJfGHptHsV3LviRRjR8bK3o4xfrk4',
    appId: '1:394471131335:ios:b6c241cb13358bed8b56e2',
    messagingSenderId: '394471131335',
    projectId: 'insightfolio-3eaf4',
    storageBucket: 'insightfolio-3eaf4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIYKjoqUp98FA2gFeVZPFA0Op_RG0_9-g',
    appId: '1:394471131335:web:70f11a13d04d77ff8b56e2',
    messagingSenderId: '394471131335',
    projectId: 'insightfolio-3eaf4',
    authDomain: 'insightfolio-3eaf4.firebaseapp.com',
    storageBucket: 'insightfolio-3eaf4.firebasestorage.app',
  );
}
